USE docker-db;

CREATE TABLE IF NOT EXISTS massagens (
    id INT PRIMARY KEY AUTO_INCREMENT,
    cliente VARCHAR(100) NOT NULL,
    data_massagem TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    tempo INT DEFAULT 60
);